In [1]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\movie_revenues.csv")
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",12/10/2009,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,54000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.youmeanddupree.com/,1819,"[{""id"": 1253, ""name"": ""roommate""}, {""id"": 2038...",en,"You, Me and Dupree",After standing in as best man for his longtime...,18.600367,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7/14/2006,130431368,108,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Two's company. Dupree's a crowd.,"You, Me and Dupree",5.4,407

In [7]:
df.revenue.describe()

count    4.600000e+01
mean     1.879289e+08
std      4.551144e+08
min      8.522060e+05
25%      2.866957e+07
50%      8.381714e+07
75%      1.382135e+08
max      2.787965e+09
Name: revenue, dtype: float64

In [12]:
df['revenue_millions']=df.revenue/1000000
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_millions
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,12/10/2009,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087
1,54000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.youmeanddupree.com/,1819,"[{""id"": 1253, ""name"": ""roommate""}, {""id"": 2038...",en,"You, Me and Dupree",After standing in as best man for his longtime...,18.600367,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,7/14/2006,130431368,108,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Two's company. Dupree's a crowd.,"You, Me and Dupree",5.4,407,130.431368

In [8]:
df['modified_z_score']=0.6745*(df.revenue-df.revenue.median())/df.revenue.mad()
df.head(2)

AttributeError: 'Series' object has no attribute 'mad'

In [13]:
_,mean,std,*_=df.revenue_millions.describe()
mean,std

(187.92889841304347, 455.1144234195408)

In [14]:
def get_z_score(x,mean,std):
    return (x-mean)/std

In [15]:
df['zscore']=df.revenue_millions.apply(lambda x:get_z_score(x,mean,std))

In [17]:
df[df['zscore']>3.5]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_millions,zscore
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087,5.712929

In [23]:
def get_mad(s):
    median=np.median(s)
    deff=abs(s-median)
    MAD=np.median(deff)
    return MAD

In [28]:
mad=get_mad(df.revenue_millions)
meadian=np.median(df.revenue_millions)
mad,meadian

(np.float64(56.399542499999995), np.float64(83.8171415))

In [31]:
def get_modified_z_score(x,median,mad):
    return 0.6745*(x-median)/mad

In [32]:
df['modified_z_score']=df.revenue_millions.apply(lambda x:get_modified_z_score(x,meadian,mad))

In [34]:
df[df['modified_z_score']>3.5]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_millions,zscore,modified_z_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087,5.712929,32.339762
7,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,124,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662,1513.528810,2.912674,17.098375
12,25000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",NaN,619,"[{""id"": 1156, ""name"": ""sister sister relations...",en,The Bodyguard,A former Secret Service agent grudgingly takes...,26.576385,"[{""name"": ""Tig Productions"", ""id"": 335}, {""nam...",...,129,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never let her out of your sight. Never let you...,The Bodyguard,6.1,661,411.006740,0.490158,3.912964

<h1>class program lab

In [1]:
from mlxtend.frequent_patterns import apriori
import pandas as pd
data = pd.DataFrame([ [1,1,0,1], [1,0,1,1], [1,1,1,0], [1,1,1,1]],
columns=['bread', 'milk','beer', 'cola'])
data = data.astype(bool)
frequent_itemsets = apriori(data,min_support=0.5)
print(frequent_itemsets)

    support              itemsets
0      1.00        frozenset({0})
1      0.75        frozenset({1})
2      0.75        frozenset({2})
3      0.75        frozenset({3})
4      0.75     frozenset({0, 1})
5      0.75     frozenset({0, 2})
6      0.75     frozenset({0, 3})
7      0.50     frozenset({1, 2})
8      0.50     frozenset({1, 3})
9      0.50     frozenset({2, 3})
10     0.50  frozenset({0, 1, 2})
11     0.50  frozenset({0, 1, 3})
12     0.50  frozenset({0, 2, 3})

In [2]:
import pyfpgrowth

transactions = [ ['Milk', 'Bread', 'Eggs'], ['Bread', 'Diaper'], ['Milk', 'Diaper', 'Eggs'],

['Bread', 'Eggs'], ['Milk', 'Bread', 'Diaper', 'Eggs']]

min_support = 2

patterns = pyfpgrowth.find_frequent_patterns (transactions, min_support)

for itemset, support in patterns.items():
 print(f"Itemset: {itemset}, Support: {support}")

Itemset: ('Milk',), Support: 3
Itemset: ('Eggs', 'Milk'), Support: 3
Itemset: ('Bread', 'Milk'), Support: 2
Itemset: ('Bread', 'Eggs', 'Milk'), Support: 2
Itemset: ('Bread', 'Diaper'), Support: 2
Itemset: ('Diaper', 'Milk'), Support: 2
Itemset: ('Diaper', 'Eggs'), Support: 2
Itemset: ('Diaper', 'Eggs', 'Milk'), Support: 2
Itemset: ('Bread',), Support: 4
Itemset: ('Eggs',), Support: 4
Itemset: ('Bread', 'Eggs'), Support: 3