In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\homeprices.csv")

In [2]:
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
dummies = pd.get_dummies(df['town']).astype(int)

In [4]:
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [5]:
merged = pd.concat([df,dummies],axis='columns')

In [18]:
merged.head()

              town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [21]:
merged.drop(['town','west windsor'],axis='columns',inplace=True)

In [22]:
merged

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [2]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [25]:
x=merged.drop('price',axis='columns')
y=merged.price

In [29]:
model.fit(x,y)

LinearRegression()

In [31]:
model.predict([[2800,1,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([565089.22812299])

In [32]:
model.predict([[3400,0,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [ ]:
model.score(x,y)

0.9573929037221872

In [34]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [35]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [41]:
x=dfle[['town','area']].values
y=dfle.price

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Suppose your first column is categorical
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])   # column index 0
    ],
    remainder='passthrough'   # keep other columns as they are
)

x = ct.fit_transform(x)

In [52]:
model.fit(x,y)

LinearRegression()

In [9]:
carprice=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\carprices.csv")
carprice

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [10]:
dummy=pd.get_dummies(carprice['Car Model']).astype(int)
dummy

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [11]:
mer=pd.concat([carprice,dummy],axis='columns')
mer

,Car Model,Mileage,Sell Price($),Age(yrs),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,0,1,0
1,BMW X5,35000,34000,3,0,1,0
2,BMW X5,57000,26100,5,0,1,0
3,BMW X5,22500,40000,2,0,1,0
4,BMW X5,46000,31500,4,0,1,0
5,Audi A5,59000,29400,5,1,0,0
6,Audi A5,52000,32000,5,1,0,0
7,Audi A5,72000,19300,6,1,0,0
8,Audi A5,91000,12000,8,1,0,0
9,Mercedez Benz C class,67000,22000,6,0,0,1
10,Mercedez Benz C class,83000,20000,7,0,0,1
11,Mercedez Benz C class,79000,21000,7,0,0,1
12,Mercedez Benz C class,59000,33000,5,0,0,1

In [12]:
mer.drop(['Car Model','BMW X5'],axis='columns',inplace=True)

In [7]:
mer

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  Mercedez Benz C class
0     69000          18000         6        0       1                      0
1     35000          34000         3        0       1                      0
2     57000          26100         5        0       1                      0
3     22500          40000         2        0       1                      0
4     46000          31500         4        0       1                      0
5     59000          29400         5        1       0                      0
6     52000          32000         5        1       0                      0
7     72000          19300         6        1       0                      0
8     91000          12000         8        1       0                      0
9     67000          22000         6        0       0                      1
10    83000          20000         7        0       0                      1
11    79000          21000         7        0       0                      1
12    59000          33000         5        0       0                      1

In [13]:
x=mer.drop('Sell Price($)',axis='columns')

In [14]:
y=mer['Sell Price($)']

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LinearRegression(),x,y)

array([  0.95838767,   0.8636328 ,   0.67087198, -18.33800887,
         0.66787517])

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [18]:
cars_salles=LinearRegression()
cars_salles.fit(x_train,y_train)

LinearRegression()

In [20]:
cars_salles.predict([[4500,1,0,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([48135.33964436])

In [19]:
cars_salles.score(x_test,y_test)

0.8659260560448166