In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data/salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [3]:
df.shape

(16, 4)

In [4]:
df['degree'].value_counts()

degree
bachelors    8
masters      8
Name: count, dtype: int64

<h1>feature engineering</h1>

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['degree'] = le.fit_transform(df['degree'])

In [6]:
df.sample(5)

       company                  job  degree  salary_more_then_100k
6   abc pharma      sales executive       1                      0
14    facebook  computer programmer       0                      1
2       google     business manager       0                      1
3       google     business manager       1                      1
9   abc pharma     business manager       1                      1

In [7]:
df.isnull().sum()

company                  0
job                      0
degree                   0
salary_more_then_100k    0
dtype: int64

In [8]:
df_encoded=pd.get_dummies(df,columns=['company','job'],drop_first=True)
df_encoded

,degree,salary_more_then_100k,company_facebook,company_google,job_computer programmer,job_sales executive
0,0,0,False,True,False,True
1,1,0,False,True,False,True
2,0,1,False,True,False,False
3,1,1,False,True,False,False
4,0,0,False,True,True,False
5,1,1,False,True,True,False
6,1,0,False,False,False,True
7,0,0,False,False,True,False
8,0,0,False,False,False,False
9,1,1,False,False,False,False
10,0,1,True,False,False,True
11,1,1,True,False,False,True
12,0,1,True,False,False,False
13,1,1,True,False,False,False
14,0,1,True,False,True,False
15,1,1,True,False,True,False

In [9]:
df_encoded.columns

Index(['degree', 'salary_more_then_100k', 'company_facebook', 'company_google',
       'job_computer programmer', 'job_sales executive'],
      dtype='str')

In [10]:
from sklearn.model_selection import train_test_split

<h1>Model training</h1>

In [11]:
from sklearn.tree import DecisionTreeClassifier

x=df_encoded.drop('salary_more_then_100k',axis='columns')
y=df_encoded['salary_more_then_100k']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
model=DecisionTreeClassifier() # deafult gimi
model.fit(x,y)

DecisionTreeClassifier()

In [12]:
from sklearn.metrics import classification_report,confusion_matrix

In [13]:
y_pred=model.predict(x_test)

report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

In [14]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[2 0]
 [0 2]]

<h1>Decision tree</h1>

In [15]:
from sklearn.tree import export_text

print(export_text(model,feature_names=list(x.columns)))

|--- company_facebook <= 0.50
|   |--- job_sales executive <= 0.50
|   |   |--- degree <= 0.50
|   |   |   |--- job_computer programmer <= 0.50
|   |   |   |   |--- company_google <= 0.50
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- company_google >  0.50
|   |   |   |   |   |--- class: 1
|   |   |   |--- job_computer programmer >  0.50
|   |   |   |   |--- class: 0
|   |   |--- degree >  0.50
|   |   |   |--- class: 1
|   |--- job_sales executive >  0.50
|   |   |--- class: 0
|--- company_facebook >  0.50
|   |--- class: 1

<h1>Entropy</h1>

In [ ]:
from sklearn.tree import DecisionTreeClassifier

x=df_encoded.drop('salary_more_then_100k',axis='columns')
y=df_encoded['salary_more_then_100k']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
model = DecisionTreeClassifier(
    criterion='gini',#how the tree evaluates the quality of a split.
    max_depth=5,# depth
    min_samples_split=10,#minimum number of samples required in a node before that node can be split.
    min_samples_leaf=5,#minimum number of samples that must remain in each leaf.
    max_features=None,#how many features the tree considers when looking for a split.
    random_state=42#controls randomness so you can get reproducible results.
)
model.fit(x,y)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [17]:
y_pred=model.predict(x_test)

report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.50      0.50         2

    accuracy                           0.50         4
   macro avg       0.50      0.50      0.50         4
weighted avg       0.50      0.50      0.50         4

In [18]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[1 1]
 [1 1]]

In [24]:
model.score(x_test,y_test)

0.5

In [19]:
print(export_text(model,feature_names=list(x.columns)))

|--- company_facebook <= 0.50
|   |--- degree <= 0.50
|   |   |--- class: 0
|   |--- degree >  0.50
|   |   |--- class: 1
|--- company_facebook >  0.50
|   |--- class: 1

In [21]:
model.predict([[1,1,1,0,1]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])